# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# AdminUser.create!(email: 'webadmin@ucbmun.com', password: '###password', password_confirmation: '###password')

# Seed attractions
Attraction.create!(image: "attractions/alcatraz.jpg", name: "Alcatraz", description: "<p>Once home to some of America’s most notorious criminals, the federal penitentiary that operated here from 1934 to 1963 brought a dark mystique to the Rock. The presence of infamous inmates like Al “Scarface” Capone, and the “Birdman” Robert Stroud helped to establish the island’s notoriety. To this day, Alcatraz is best known as one of the world’s most legendary prisons. </p> <p> <b> Open: </b> 9AM - 4:30PM <br /> <b> Price: </b> $30 <br /> <b> Phone: </b> (415)-561-4900 </p> ")
Attraction.create!(image: "attractions/angel.jpg", name: "Angel Island", description: "<p>Angel Island is a California Historical Landmark, previously used for militarily forts and an immigration station. Between 1910 and 1940, this immigration station process approximately 1 million Asian immigrants entering the United States. Sitting as the largest island in the San Francisco area, Angel Island provides a beautiful view of San Francisco and its neighboring cities. </p> <p> <b> Price: </b> $7 <br /> <b> Phone: </b> (415)-438-8361 </p> ")
Attraction.create!(image: "attractions/goldenpark.jpg", name: "Golden Gate Park", description: "<p>The Golden Gate Park is a great place to see many attractions all in one location! This large vicinity holds many activities such as Segway tours, a carousel, the de Young museum, Japanese tea garden and many more! The park is also known to hold many free concerts and is a great place to enjoy some fun in the sun! </p> <p> <b> Open: </b> M-Sat: 9:30-5; Sunday: 11-5 <br /> <b> Price: </b> Free <br /> <b> Phone: </b> (415)-831-2700 </p> ")
Attraction.create!(image: "attractions/exploratorium.jpg", name: "The Exploratorium", description: "<p>Become a science explorer at San Francisco’s most unique learning laboratory! The Exploratorium takes education to a whole new level with its hands on interactive exhibits and attraction. Founded by the famous physicist Frank Oppenheimer, this museum provides entertainment for all ages! Its latest attraction, on Thursday nights, is dedicated to guests 21 and over. </p> <p> <b> Open: </b> 10AM - 5PM <br /> <b> Price: </b> $25 <br /> <b> Phone: </b> (415)-528-4444 <br /> <b> Location: </b> Pier 15(Embarcadero at Green St) <br /> <b> Distance: </b> Approx 1 mile (15 min walking from the hotel) </p> ")
Attraction.create!(image: "attractions/museum.jpg", name: "De Young Museum", description: "<p>When visiting the Golden Gate Park, stop by the de Young Museum! The de Young is a fine arts museum well known for his exquisite exhibitions and collections. Its new building, remodeled in 2005, is a site to see on its own! </p> <p> <b> Open: </b> 9:30AM - 5:15PM <br /> <b> Price: </b> $7(students), $11(adults)<br /> <b> Phone: </b> 415-750-3600 <br /> <b> Location: </b> 50 Hagiwara Tea Garden Drive (within Golden Gate Park)<br /> <b> Distance: </b> 6 miles (approx. 45 min by public transit from the hotel) </p> ")
Attraction.create!(image: "attractions/fishermans.jpg", name: "Fisherman's Wharf", description: "<p>Fisherman’s Wharf is conveniently located right beside Pier 39. This historic part of San Francisco holds great entertainment, shopping, and delicious dining! Come enjoy a nice big bread bowl of clam chowder. Fisherman’s Wharf is also a great place to catch a ride on a cable car! </p> <p> <b> Open: </b> 10AM - 9PM <br /> <b> Price: </b> Free <br /> <b> Number: </b> (415)-981-7437 <br /> <b> Location: </b> Pier 39 Concourse, San Francisco, CA <br /> <b> Distance: </b> 1.6 miles (approx 20 by walking from the hotel) </p> ")
Attraction.create!(image: "attractions/goldenbridge.jpg", name: "Golden Gate Bridge", description: "<p>The Golden Gate Bridge connects San Francisco to California’s northern counties! With its gigantic 746 foot tall towers and more than 10 million annual visitors, the bridge has acted as San Francisco’s most iconic landmark. Visitors can run or rent bikes along the bridge or visit the all new Bridge Plaza for visitor experiences located at the south east end. </p> <p> <b> Open: </b> 5AM - 6:30PM <br /> <b> Price: </b> $5(students), $7(adults)<br /> <b> Number: </b> (415)-921-5858<br /> </p> ")
Attraction.create!(image: "attractions/academy.jpg", name: "California Academy of Sciences", description: "<p>The California Academy of sciences is one of the largest museums exhibiting the natural history of the world. Its staff and faculty are motivated by two questions: How did life on Earth develop and how will we sustain life on Earth? This entertaining and interactive music will keep you informed of the latest research through their exciting venues, exhibits and animals. </p> <p> <b> Open: </b> 9:30AM - 5PM; Sundays: 11AM-5PM<br /> <b> Price: </b> $29.95<br /> <b> Number: </b> (415)-379-8000 <br /> <b> Location: </b> 55 Music Concourse Dr, San Francisco, CA 94118 <br /> <b> Distance: </b> 6 miles (approx 45 min by public transit from the hotel) </p> ")
Attraction.create!(image: "attractions/lombard.jpg", name: "Lombard Street", description: "<p>Lombard Street is famous for being San Francisco’s “crookedest”street with eight tight hairpin turns. This street is located on a steep hill, embellished with the most beautiful and exotic flowers. Its beauty is known worldwide and has made appearances in many films and television series! </p> <p> <b> Open: </b> All hours <br /> <b> Price: </b> Free <br /> <b> Location: </b> Lombard St <br /> <b> Distance: </b> 2.7 mi (approx 25 min by public transit from the hotel) </p> ")
Attraction.create!(image: "attractions/powell.jpg", name: "Powell St. Cable Cars", description: "<p>The San Francisco cable car system is the world’s last manually operated cable car system! This San Francisco icon once has twenty three lines which were established in 1873, with only three currently remaining. These lines are on Powell-Hyde, Powell-Mason, and California Street. The cable cars are a fun way to visit San Francisco’s most touristic attractions such as the Golden Gate Bridge and Fisherman’s Wharf. </p> <p> <b> Open: </b> 10AM - 5PM <br /> <b> Price </b> $5 <br />  </p> ")
Attraction.create!(image: "attractions/ghiradelli.jpg", name: "Ghiradelli Square", description: "<p>Calling all chocolate lovers! Ghirardelli Squre is a historic San Francisco visitor attraction offering shopping, waterfront dining, family events, Ghirardelli chocolate and walking tours. This landmark once featured over 40 specialty shops and restaurants with some of the originals still operating. Come enjoy a large milkshake or a sundae drenched in Ghirardelli chocolate! </p> <p> <b> Open: </b> 9AM - 11PM <br /> <b> Number: </b> (415) 775-5500<br /> <b> Location: </b> 900 North Point Street <br /> <b> Distance: </b> 1.3 miles (approx 25 min walk from the hotel); </p> ")
Attraction.create!(image: "attractions/coittower.jpg", name: "Coit Tower", description: "<p>Coit Tower is located in the Telegraph Hill neighborhood of San Francisco, California. Lillian Coit, a San Francisco socialite, requested that one-third of her estate to the city be directed to civic beautification. Built in 1931, Coit Tower is home to many exquisite paintings and murals and a beautiful view of the city at the top. </p> <p> <b> Open: </b> 10AM - 5:30PM <br /> <b> Price: </b> $7 <br /> <b> Number: </b> (415) 362-0808 <br /> <b> Location: </b> 1 Telegraph Hill Blvd <br /> <b> Distance: </b> 0.9 miles (approx 15 min walk from the hotel) </p> ")
Attraction.create!(image: "attractions/twinpeaks.jpg", name: "Twin Peaks", description: "<p>The Twin Peaks are one of the two highest points in the city! These two hills sit with an elevation of about 922 feet near the center of San Francisco. They offer beautiful unobstructed views of most of the city and the San Francisco Bay! </p> <p> <b> Open: </b> 9AM - 4:30PM <br /> <b> Price: </b> Free <br /> <b> Phone: </b> (415)-864-9470 </p> ")
Attraction.create!(image: "attractions/presidio.jpg", name: "The Presidio", description: "<p>The Presidio is a national park service that once served as a military base. With five different visitor center this San Francisco landmark offers a blast to the past to the Mexican-American war in 1846. The park has approximately 800 buildings in the park’s vicinity with one of its most visited being the Walt Disney Family Museum, a museum to honor the memory of the great Walt Disney. </p> <p> <b> Open: </b> 9AM - 5PM <br /> <b> Price: </b> Free <br /> <b> Phone: </b> (415)-561-4323 </p> ")
Attraction.create!(image: "attractions/aquarium.jpg", name: "Aquarium of the Bay", description: "<p>Located on Pier 39, the Aquarium of the Bay is a public aquarium that focuses on the local marine animals. The exhibit is divided into three parts, Discover the Bay, Under the Bay, and Touch the Bay all of which are interactive and education. Get to know San Francisco’s most unique inhabitants such as over 50 shark species, skates, bat rays and many other aquatic animals! </p> <p> <b> Open: </b> 10AM - 6PM <br /> <b> Price: </b> $21.95 <br /> <b> Phone: </b> (415)-623-5300 </p> ")
Attraction.create!(image: "attractions/embarcadero.jpg", name: "The Embarcadero", description: "<p>The San Francisco Ferry Building is a terminal for ferries that travel across the San Francisco Bay but also holds one of the most unique marketplaces. With goods and services from all around the world, the Ferry Building accurately depicts San Francisco’s culture. Enjoy a nice cup of coffee or ice cream cone in their beautiful courtyard as you walk through their outside market. </p> <p> <b> Open: </b> M-F:10AM-6PM; Sat:9AM-6PM; Sun: 11AM-5PM <br /> <b> Price: </b> Free <br /> <b> Phone: </b> (415)-983-8030 </p>  ")
